# Generated by Django 5.2.6 on 2025-11-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promguest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
