# Generated by Django 5.2.6 on 2025-09-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='guests/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de confirmação'),
        ),
    ]
